@baseUrl = https://emptyplace.duckdns.org
@adminToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuZXd1c2VyQHRlc3QuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzg5ODA0OTAzLCJleHAiOjE3ODk4MDg1MDN9.kGT2FDkOFwHKugoC27oNATntJCop1iIQBb6eP0haI7s

PUT {{baseUrl}}/admin/products/68/active
Authorization: Bearer {{adminToken}}