GET https://emptyplace.duckdns.org/addresses
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJza3Ntc3Nucm4zNzlAZ21haWwuY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3ODk5ODI3NjMsImV4cCI6MTc4OTk4NjM2M30.KVaE6bFvDIbAXjrfnk-HbyKWKMv9JsR40CdMNVJ_t1E
