spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/upgradehub}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=${PORT:8080}
jwt.secret=$${JWT_SECRET:upgradehub-secret-key-upgradehub-secret-key}


toss.secret-key=${TOSS_SECRET_KEY:test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6} 